version: '3.8'

services:
  warehouse-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
